from ezmatrix import *
from animation import *
from modules import *

from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

import time
import json
import threading

endpoint = 'avhmfui1t673z.iot.us-west-2.amazonaws.com'
root_ca_path = '/home/pi/Desktop/aws/root-CA.crt'
certificate_path = '/home/pi/Desktop/aws/RaspPi.cert.pem'
private_key_path = '/home/pi/Desktop/aws/RaspPi.private.key'

topic = 'rpi/desktopbuddy'

matrix = EzMatrix()

class ClockAttributes(object):
    def __init__(self, json):
        self.unit = json['unit']
        self.zip_code = json['zip_code']
        self.region = json['region']
        
        temp_color_json = json['temp_color']
        self.temp_color = Color(temp_color_json['r'], temp_color_json['g'], temp_color_json['b'])
        
        day_color_json = json['day_color']
        self.day_color = Color(day_color_json['r'], day_color_json['g'], day_color_json['b'])
        
        date_color_json = json['date_color']
        self.date_color = Color(date_color_json['r'], date_color_json['g'], date_color_json['b'])
        
        hour_color_json = json['hour_color']
        self.hour_color = Color(hour_color_json['r'], hour_color_json['g'], hour_color_json['b'])
    
        minute_color_json = json['minute_color']
        self.minute_color = Color(minute_color_json['r'], minute_color_json['g'], minute_color_json['b'])

class AnimationThread(threading.Thread):
    def __init__(self, anim=None):
        super(AnimationThread, self).__init__()
        self.should_stop = False
        self.anim = anim
        
    def run(self):
        while not self.should_stop:
            matrix.run_anim(self.anim)
            
class ClockThread(threading.Thread):
    def __init__(self, ref_rate, unit, zip_code, region, temp_color, day_color, date_color, hour_color, minute_color):
        super(ClockThread, self).__init__()
        self.should_stop = False
        self.ref_rate = ref_rate * 60 # convert ref_rate from minutes to seconds
        self.unit = unit
        self.zip_code = zip_code
        self.region = region
        self.temp_color = temp_color
        self.day_color = day_color
        self.date_color = date_color
        self.hour_color = hour_color
        self.minute_color = minute_color
        
    def run(self):
        temp_cvs = Module.temperature_canvas(self.unit, self.zip_code, self.temp_color)
        
        tme = int(time.time())
        
        while not self.should_stop:
            if int(time.time()) - tme == self.ref_rate:
                temp_cvs = Module.temperature_canvas(self.unit, self.zip_code, self.temp_color)
                tme = int(time.time())
                
            time_cvs = Canvas(25, 19).add_subcanvas(
                Module.time_canvas(
                    self.region,
                    self.day_color,
                    self.date_color,
                    self.hour_color,
                    Color.red(),
                    self.minute_color), Point(0, 6))
            
            time_cvs.add_subcanvas(temp_cvs, Point(9, 0))
            
            matrix.draw_canvas(Canvas().add_subcanvas(time_cvs, Point(3, 6)))

class CallbackContainer(object):
    def __init__(self, client):
        self._client = client
        self.thread = AnimationThread()
        
    def interpritMessage(self, client, userdata, message):
        try:
            msg = json.loads(message.payload)['message']
        except ValueError:
            print('MISSING DELIMITER IN JSON')
        
        if 'args' in message.payload:
            args = json.loads(message.payload)['args']
        else:
            args = ''
        
        print('Message received: \"{}\" from topic {}'.format(msg, message.topic))
        
        if self.thread.isAlive():
            print('JOINING THREAD')
            self.thread.should_stop = True
            self.thread.join()

        if 'clock' in msg:
            clock_attrs = ClockAttributes(args)
            
            self.thread = ClockThread(
                3,
                clock_attrs.unit,
                clock_attrs.zip_code,
                clock_attrs.region,
                clock_attrs.temp_color,
                clock_attrs.day_color,
                clock_attrs.date_color,
                clock_attrs.hour_color,
                clock_attrs.minute_color)
            
            self.thread.should_stop = False
            self.thread.start()
        if 'image' in msg:
            ''' display image '''
            pass
        if 'gif' in msg:
            args = './gifs/' + args + '.gif'
            
            anim = Module.gif_anim(args)
            
            self.thread = AnimationThread(anim)
            self.thread.should_stop = False
            self.thread.start()

if __name__ == "__main__":
    print('STARTING...')
    client = AWSIoTMQTTClient('desktopBuddy')
    # the argument in above line is the clientID, if left empty it will be randomly generated by AWS
    client.configureEndpoint(endpoint, 8883)
    client.configureCredentials(root_ca_path, private_key_path, certificate_path)

    client.configureAutoReconnectBackoffTime(1, 32, 20)
    client.configureOfflinePublishQueueing(-1)
    client.configureDrainingFrequency(2)
    client.configureConnectDisconnectTimeout(10)
    client.configureMQTTOperationTimeout(5)

    myCallbackContainer = CallbackContainer(client)

    client.connect()

    client.subscribe(topic, 1, myCallbackContainer.interpritMessage)
    print('STARTED SERVICE')

    while True:
        time.sleep(3)